"""
Run inference on test portfolios and report errors (predicted vs actual).

Loads portfolios from data/test_portfolios/ (e.g. generated by
generate_test_portfolios.py), runs the same inference path as the GUI
(recommend_portfolio_strategy), and writes a report.

Output:
    data/test_portfolios/report.xlsx  (primary) with 3 sheets:
      1. with_Product   - report where Product feature is used to predict
      2. no_Product     - report where Product feature is excluded from predictions
      3. comparison     - side-by-side comparison of the two
    data/test_portfolios/report.csv   - comparison data in CSV form

Usage:
    python scripts/run_portfolio_tests.py
"""

import os
import sys

import pandas as pd

# Run from project root so imports and config paths work
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
os.chdir(PROJECT_ROOT)

# So joblib can unpickle scalers saved when split.py was run as __main__ (they reference __main__.LogStandardScaler)
import split as _split_module
sys.modules["__main__"].LogStandardScaler = getattr(_split_module, "LogStandardScaler", None)

from predict import load_artifacts_for_inference, recommend_portfolio_strategy


def main():
    portfolios_dir = os.path.join("data", "test_portfolios")
    if not os.path.isdir(portfolios_dir):
        print(f"Directory not found: {portfolios_dir}")
        print("Run scripts/generate_test_portfolios.py first.")
        return 1

    try:
        load_artifacts_for_inference()
    except Exception as e:
        print(f"Failed to load model artifacts: {e}")
        print("Train the model first (e.g. via GUI Training tab or train.py).")
        return 1

    xlsx_files = sorted(
        [f for f in os.listdir(portfolios_dir) if f.endswith(".xlsx") and not f.startswith("report")]
    )
    if not xlsx_files:
        print(f"No .xlsx files in {portfolios_dir}")
        return 1

    rows = []
    rows_no_product = []

    for f in xlsx_files:
        path = os.path.join(portfolios_dir, f)
        name = os.path.splitext(f)[0]
        try:
            df = pd.read_excel(path)
        except Exception as e:
            print(f"  {f}: read error - {e}")
            rows.append({
                "portfolio": name,
                "file": f,
                "n_cases": None,
                "total_actual": None,
                "total_predicted_with_product": None,
                "error_with_product": None,
                "rel_error_with_product_pct": None,
                "status": f"read error: {e}",
            })
            rows_no_product.append({
                "portfolio": name,
                "file": f,
                "n_cases": None,
                "total_actual": None,
                "total_predicted_no_product": None,
                "error_no_product": None,
                "rel_error_no_product_pct": None,
                "status": f"read error: {e}",
            })
            continue

        if "Paid Value" not in df.columns:
            msg = "no 'Paid Value' column, skipping"
            print(f"  {f}: {msg}")
            rows.append({
                "portfolio": name,
                "file": f,
                "n_cases": len(df),
                "total_actual": None,
                "total_predicted_with_product": None,
                "error_with_product": None,
                "rel_error_with_product_pct": None,
                "status": msg,
            })
            rows_no_product.append({
                "portfolio": name,
                "file": f,
                "n_cases": len(df),
                "total_actual": None,
                "total_predicted_no_product": None,
                "error_no_product": None,
                "rel_error_no_product_pct": None,
                "status": msg,
            })
            continue

        total_actual = float(pd.to_numeric(df["Paid Value"], errors="coerce").fillna(0).sum())

        # === Run with full feature set (including Product) ===
        try:
            result_with = recommend_portfolio_strategy(df)
            if "Optimal_Predicted_Value" not in result_with.columns:
                raise RuntimeError("no Optimal_Predicted_Value in result")
            total_pred_with = float(result_with["Optimal_Predicted_Value"].sum())
            error_with = total_pred_with - total_actual
            rel_with = (error_with / total_actual * 100.0) if total_actual != 0 else None
            status_with = "ok"
        except Exception as e:
            print(f"  {f}: inference error (with Product) - {e}")
            total_pred_with = None
            error_with = None
            rel_with = None
            status_with = f"with Product: {e}"

        # === Run with Product variation removed ===
        df_no_product = df.copy()
        if "Product" in df_no_product.columns:
            # Collapse Product variation so the model cannot exploit per-product differences.
            df_no_product["Product"] = "NeutralProduct"

        try:
            result_no_prod = recommend_portfolio_strategy(df_no_product)
            if "Optimal_Predicted_Value" not in result_no_prod.columns:
                raise RuntimeError("no Optimal_Predicted_Value in result")
            total_pred_no = float(result_no_prod["Optimal_Predicted_Value"].sum())
            error_no = total_pred_no - total_actual
            rel_no = (error_no / total_actual * 100.0) if total_actual != 0 else None
            status_no = "ok"
        except Exception as e:
            print(f"  {f}: inference error (no Product) - {e}")
            total_pred_no = None
            error_no = None
            rel_no = None
            status_no = f"no Product: {e}"

        rows.append({
            "portfolio": name,
            "file": f,
            "n_cases": len(df),
            "total_actual": round(total_actual, 2),
            "total_predicted_with_product": round(total_pred_with, 2) if total_pred_with is not None else None,
            "error_with_product": round(error_with, 2) if error_with is not None else None,
            "rel_error_with_product_pct": round(rel_with, 2) if rel_with is not None else None,
            "status": status_with,
        })

        rows_no_product.append({
            "portfolio": name,
            "file": f,
            "n_cases": len(df),
            "total_actual": round(total_actual, 2),
            "total_predicted_no_product": round(total_pred_no, 2) if total_pred_no is not None else None,
            "error_no_product": round(error_no, 2) if error_no is not None else None,
            "rel_error_no_product_pct": round(rel_no, 2) if rel_no is not None else None,
            "status": status_no,
        })

        # Print quick comparison to console
        if status_with == "ok" and status_no == "ok":
            print(
                f"  {name}: actual={total_actual:,.0f}, "
                f"with_prod={total_pred_with:,.0f} ({rel_with:.1f}%), "
                f"no_prod={total_pred_no:,.0f} ({rel_no:.1f}%)"
            )
        else:
            print(f"  {name}: {status_with} | {status_no}")

    if not rows:
        print("No results to report.")
        return 0

    report_with = pd.DataFrame(rows)
    report_no = pd.DataFrame(rows_no_product)

    # Filter only successful rows for summary stats
    ok_with = report_with[report_with["status"] == "ok"]
    ok_no = report_no[report_no["status"] == "ok"]

    def _print_summary(label: str, df: pd.DataFrame, err_col: str, pct_col: str) -> None:
        if len(df) == 0:
            print(f"\nNo successful portfolios for {label}.")
            return
        mae = df[err_col].abs().mean()
        rmse = (df[err_col] ** 2).mean() ** 0.5
        print(f"\n{label} - MAE (total predicted vs actual): {mae:,.2f}")
        print(f"{label} - RMSE: {rmse:,.2f}")
        if df[pct_col].notna().any():
            print(f"{label} - Mean |rel error| %: {df[pct_col].abs().mean():.1f}%")

    _print_summary("With Product", ok_with, "error_with_product", "rel_error_with_product_pct")
    _print_summary("No Product", ok_no, "error_no_product", "rel_error_no_product_pct")

    # Comparison dataframe (for the Excel report)
    compare_cols = [
        "portfolio",
        "file",
        "n_cases",
        "total_actual",
        "total_predicted_with_product",
        "error_with_product",
        "rel_error_with_product_pct",
        "total_predicted_no_product",
        "error_no_product",
        "rel_error_no_product_pct",
    ]
    compare_df = report_with.merge(
        report_no[
            [
                "portfolio",
                "file",
                "total_predicted_no_product",
                "error_no_product",
                "rel_error_no_product_pct",
            ]
        ],
        on=["portfolio", "file"],
        how="left",
    )[compare_cols]

    # Primary report: .xlsx with 3 sheets
    report_xlsx_path = os.path.join(portfolios_dir, "report.xlsx")
    try:
        with pd.ExcelWriter(report_xlsx_path, engine="openpyxl") as writer:
            # Sheet 1: Report where Product feature is used to predict
            report_with.to_excel(writer, sheet_name="with_Product", index=False)
            # Sheet 2: Report where Product feature is excluded from predictions
            report_no.to_excel(writer, sheet_name="no_Product", index=False)
            # Sheet 3: Comparison of the two
            compare_df.to_excel(writer, sheet_name="comparison", index=False)
        print(f"\nReport saved to {report_xlsx_path} (3 sheets: with_Product, no_Product, comparison)")
    except Exception as e:
        try:
            # Fallback without specifying engine
            with pd.ExcelWriter(report_xlsx_path) as writer:
                report_with.to_excel(writer, sheet_name="with_Product", index=False)
                report_no.to_excel(writer, sheet_name="no_Product", index=False)
                compare_df.to_excel(writer, sheet_name="comparison", index=False)
            print(f"\nReport saved to {report_xlsx_path} (3 sheets: with_Product, no_Product, comparison)")
        except Exception as e2:
            print(f"\nFailed to write Excel report: {e2}")
            print("Install openpyxl for .xlsx support: pip install openpyxl")

    # Optional CSV export (same comparison data)
    report_csv_path = os.path.join(portfolios_dir, "report.csv")
    compare_df.to_csv(report_csv_path, index=False)
    print(f"Comparison CSV saved to {report_csv_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
